In [2]:
#import libraries
import pandas as pd
pd.set_option('display.max_columns', None)

In [3]:
#loading the data
movies = pd.read_csv("movies.csv")
ratings = pd.read_csv("ratings.csv")

In [7]:
print("Movies CSV:")
display(movies.head(5))
print("\nRatings CSV:")
display(ratings.head(5))

Movies CSV:

,id,title,genres,overview,cast,director,release_date,popularity,vote_average,vote_count,poster_url
0,1523145,Your Heart Will Be Broken,"Romance, Drama",High school student Polina is saved from bully...,"Daniel Vegas, Veronika Zhuravleva, Ivan Trushi...",Mikhail Vaynberg,2026-03-26,1043.4595,7.000,21,https://image.tmdb.org/t/p/w500/7wIBfBl2gejt6x...
1,83533,Avatar: Fire and Ash,"Science Fiction, Adventure, Fantasy",In the wake of the devastating war against the...,"Sam Worthington, Zoe Saldaña, Sigourney Weaver...",James Cameron,2025-12-17,369.7046,7.276,2019,https://image.tmdb.org/t/p/w500/bRBeSHfGHwkEpI...
2,1084187,Pretty Lethal,"Action, Thriller",A troupe of ballerinas find themselves fightin...,"Maddie Ziegler, Lana Condor, Iris Apatow, Mill...",Vicky Jewson,2026-03-13,304.1287,6.777,146,https://image.tmdb.org/t/p/w500/znTPnXCK3lEQJg...
3,1115544,Mike & Nick & Nick & Alice,"Comedy, Science Fiction, Crime",Two gangsters and the woman they love try to s...,"James Marsden, Vince Vaughn, Eiza González, Ke...",BenDavid Grabinski,2026-03-14,323.4594,6.752,101,https://image.tmdb.org/t/p/w500/7F0jc75HrSkLVc...
4,1290821,Shelter,"Action, Crime, Thriller",A man living in self-imposed exile on a remote...,"Jason Statham, Bodhi Rae Breathnach, Michael S...",Ric Roman Waugh,2026-01-28,284.1759,6.729,435,https://image.tmdb.org/t/p/w500/buPFnHZ3xQy6vZ...

Ratings CSV:

   userId  movieId  rating
0       1  1208348     7.9
1       1  1193501     6.0
2       1   561362     5.6
3       1   434853     5.6
4       1    10867     7.4

In [9]:
#drop movies with missing essential info
movies.dropna(subset=['title','genres','overview'], inplace=True)

In [11]:
#fill missing values
movies['cast']= movies['cast'].fillna('Unknown')
movies['director']= movies['cast'].fillna('Unknown')
movies['release_date']= movies['cast'].fillna('Unknown')
movies['poster_url']= movies['cast'].fillna('Unknown')

In [12]:
#remove duplicates
movies.drop_duplicates(subset='id', inplace=True)

In [14]:
#convert text to lowercase
movies['title']= movies['title'].str.lower()
movies['title']= movies['overview'].str.lower()
movies['title']= movies['genres'].str.lower()

In [15]:
print("Movies cleaned:", movies.shape)
display(movies.head())

Movies cleaned: (955, 11)

,id,title,genres,overview,cast,director,release_date,popularity,vote_average,vote_count,poster_url
0,1523145,"romance, drama","Romance, Drama",High school student Polina is saved from bully...,"Daniel Vegas, Veronika Zhuravleva, Ivan Trushi...","Daniel Vegas, Veronika Zhuravleva, Ivan Trushi...","Daniel Vegas, Veronika Zhuravleva, Ivan Trushi...",1043.4595,7.000,21,"Daniel Vegas, Veronika Zhuravleva, Ivan Trushi..."
1,83533,"science fiction, adventure, fantasy","Science Fiction, Adventure, Fantasy",In the wake of the devastating war against the...,"Sam Worthington, Zoe Saldaña, Sigourney Weaver...","Sam Worthington, Zoe Saldaña, Sigourney Weaver...","Sam Worthington, Zoe Saldaña, Sigourney Weaver...",369.7046,7.276,2019,"Sam Worthington, Zoe Saldaña, Sigourney Weaver..."
2,1084187,"action, thriller","Action, Thriller",A troupe of ballerinas find themselves fightin...,"Maddie Ziegler, Lana Condor, Iris Apatow, Mill...","Maddie Ziegler, Lana Condor, Iris Apatow, Mill...","Maddie Ziegler, Lana Condor, Iris Apatow, Mill...",304.1287,6.777,146,"Maddie Ziegler, Lana Condor, Iris Apatow, Mill..."
3,1115544,"comedy, science fiction, crime","Comedy, Science Fiction, Crime",Two gangsters and the woman they love try to s...,"James Marsden, Vince Vaughn, Eiza González, Ke...","James Marsden, Vince Vaughn, Eiza González, Ke...","James Marsden, Vince Vaughn, Eiza González, Ke...",323.4594,6.752,101,"James Marsden, Vince Vaughn, Eiza González, Ke..."
4,1290821,"action, crime, thriller","Action, Crime, Thriller",A man living in self-imposed exile on a remote...,"Jason Statham, Bodhi Rae Breathnach, Michael S...","Jason Statham, Bodhi Rae Breathnach, Michael S...","Jason Statham, Bodhi Rae Breathnach, Michael S...",284.1759,6.729,435,"Jason Statham, Bodhi Rae Breathnach, Michael S..."

In [19]:
#drop missing values
ratings.dropna(subset=['userId','movieId','rating'], inplace=True)

In [20]:
#convert ids to integer
ratings['userId']= ratings['userId'].astype(int)
ratings['movieId']= ratings['movieId'].astype(int)

In [21]:
#remove duplicates
ratings.drop_duplicates(subset=['userId','movieId'], inplace=True)

In [22]:
#clip ratings to valid range (0-10)
ratings['rating']= ratings['rating'].clip(0,10)

In [25]:
print("Ratings Cleaned:", ratings.shape)
display(ratings.head())

Ratings Cleaned: (3574, 3)

   userId  movieId  rating
0       1  1208348     7.9
1       1  1193501     6.0
2       1   561362     5.6
3       1   434853     5.6
4       1    10867     7.4

In [26]:
#saving clean data to new csv files
movies.to_csv("movies_cleaned.csv", index=False)
ratings.to_csv("ratings_cleaned.csv", index=False)

print("Cleaned CSV files saved!")

Cleaned CSV files saved!